### ISSUE TITLE
feature requests - select video resolution

### ISSUE THREAD

**Issue by Eilaluth** [sleepntsheep/ani-cli#1]
This project really cool, easy to use and can be used in windows without problem with mpv,
and because of that im really hope you will add feature to select resolution before searching the anime.

kinda sad that what i can do is only requesting feature instead contribute, i can not contribute becausei i dont understand python but i really like this project and i hope you will add this feature in future.

thanks

**Comment by sleepntsheep** [comment]
Thanks! I will try to implement this

**Comment by sleepntsheep** [comment]
implemented in [https://github.com/sleepntsheep/ani-cli/commit/78f489ba14dcfe5c6812ae35711e317e3f2ff798](78f489b) [https://github.com/sleepntsheep/ani-cli/commit/d446cebb008ea3e758e120cb9e915c348870e24e](d446ceb)
